AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/Documentation:
  Enabled: false
