default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("SQLITE_DB_PATH", "./data/app.db") %>

test:
  <<: *default
  database: <%= ENV.fetch("SQLITE_DB_PATH", "./data/test.db") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("SQLITE_DB_PATH", "./data/app.db") %>
  queue:
    <<: *default
    database: <%= ENV.fetch("SOLID_QUEUE_DB_PATH", "./data/queue_production.sqlite3") %>
    migrations_paths: db/queue_migrate
